[package]
name = "sumfill"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sumfill"
path = "src/main.rs"

[[bin]]
name = "sumfill2"
path = "src/main2.rs"

[[bin]]
name = "sumfillcl"
path = "src/maincl.rs"

[dependencies]
rayon = "1.6"
"opencl3" = "0.9"
